<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_code = $this->getMethodCode();
$_customer = Mage::getSingleton('customer/session')->getCustomer();

if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $billingAddress = Mage::getModel('customer/address')->load($_customer->getDefaultBilling());
    $countryId = $billingAddress->getCountry();
} else {
    $billingAddress = Mage::getSingleton('checkout/session')
        ->getQuote()
        ->getBillingAddress()
        ->getData();
    $countryId = isset($billingAddress['country_id']) ? $billingAddress['country_id'] : null;
}

$addressIsValid = in_array(strtoupper($countryId), array('NL', 'BE'));

$termsConditionsUrl = 'https://www.afterpay.nl/nl/algemeen/betalen-met-afterpay/betalingsvoorwaarden';
if (strtoupper($countryId) == 'BE') {
    $termsConditionsUrl = 'https://www.afterpay.be/be/footer/betalen-met-afterpay/betalingsvoorwaarden';
}

if ($addressIsValid) {
    $_gender = $this->getLayout()
        ->createBlock('customer/widget_gender')
        ->setGender($_customer->getGender())
        ->setFieldNameFormat('afterpay_gender')
        ->setFieldIdFormat('afterpay_gender');

    $_dob = $this->getLayout()
        ->createBlock('customer/widget_dob')
        ->setFieldIdFormat('afterpay_dob')
        ->setFieldNameFormat('afterpay_dob')
        ->setDate($_customer->getDob());
}
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if ($addressIsValid): ?>
        <?php if (!$_dob->isRequired()): ?>
            <li>
                <div class="input-box">
                    <?php echo $_dob->toHtml(); ?>
                </div>
            </li>
        <?php endif; ?>
        <?php if (!$_gender->isRequired()): ?>
            <li>
                <div class="input-box">
                    <?php echo $_gender->toHtml(); ?>
                </div>
            </li>
        <?php endif; ?>
        <input type="checkbox"
               id="afterpay-terms-conditions"
               name="afterpay-terms-conditions"
               class="checkbox required-entry">
        <?php echo $this->__('I accept AfterPay'); ?>
        <a href="<?php echo $termsConditionsUrl; ?>" target="_blank">
            <?php echo $this->__('Terms & Conditions'); ?>
        </a>
    <?php else: ?>
        <li>
            <?php echo $this->__('Unfortunately, you cannot use AfterPay as Afterpay is only available for addresses in the Netherlands and Belgium. Please use the correct address or select another payment method.'); ?>
        </li>
    <?php endif; ?>
</ul>