<?php
/**
 *   ╲          ╱
 * ╭──────────────╮  COPYRIGHT (C) 2019 GINGER PAYMENTS B.V.
 * │╭──╮      ╭──╮│
 * ││//│      │//││
 * │╰──╯      ╰──╯│
 * ╰──────────────╯
 *   ╭──────────╮    The MIT License (MIT)
 *   │ () () () │
 *
 * @category    EMS
 * @package     EMS_Payment
 * @author      Ginger Payments B.V. (info@gingerpayments.com)
 * @copyright   COPYRIGHT (C) 2019 GINGER PAYMENTS B.V. (https://www.gingerpayments.com)
 * @license     The MIT License (MIT)
 */
?>
<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <li>
        <label for="<?php echo $this->getMethodCode() ?>_issuer_id" class="required">
            <em>*</em><?php echo $this->__('Choose your bank:') ?>
        </label>
        <span class="input-box">
            <select name="issuer_id"
                    class="required-entry input-text"
                    id="<?php echo $this->getMethodCode(); ?>_issuer_id"
                    title="<?php echo $this->getMethodCode() ?>_issuer_id">
                <?php foreach ($this->getMethod()->getIssuers() as $issuer): ?>
                    <?php if (isset($issuer['id']) && isset($issuer['id'])): ?>
                        <option value="<?php echo $issuer['id'] ?>"><?php echo $issuer['name'] ?></option>
                    <?php endif ?>
                <?php endforeach ?>
            </select>
        </span>
    </li>
</ul>