<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<?php
$_code = $this->getMethodCode();
$_customer = Mage::getSingleton('customer/session')->getCustomer();

$_gender = $this->getLayout()
    ->createBlock('customer/widget_gender')
    ->setFieldNameFormat('klarna_gender')
    ->setFieldIdFormat('klarna_gender')
    ->setGender($_customer->getGender());

$_dob = $this->getLayout()
    ->createBlock('customer/widget_dob')
    ->setFieldNameFormat('klarna_dob')
    ->setFieldIdFormat('klarna_dob')
    ->setDate($_customer->getDob());

?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <?php if (!$_dob->isRequired()): ?>
        <li>
            <div class="input-box">
                <?php echo $_dob->toHtml(); ?>
            </div>
        </li>
    <?php endif; ?>
    <?php if (!$_gender->isRequired()): ?>
        <li>
            <div class="input-box">
                <?php echo $_gender->toHtml(); ?>
            </div>
        </li>
    <?php endif; ?>
</ul>