<?php
/**
 * Copyright © Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<p><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></p>
<?php if ($this->getInfo()->getAdditionalData()): ?>
    <?php if ($this->getMailingAddress()): ?>
        <p><strong><?php echo Mage::helper('payment')->__('Payment instructions:') ?></strong></p>
        <address class="checkmo-mailing-address">
            <?php echo nl2br($this->escapeHtml($this->getMailingAddress())) ?>
        </address>
    <?php endif ?>
<?php endif ?>
